version: "3"

tasks:
  build:
    desc: Build the box binary
    cmds:
      - go build -o box main.go

  build-linux:
    desc: Build the box binary for linux
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o box main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  serve-docs:
    desc: Serve documentation
    cmds:
      - go run . run mkdocs serve