version: "3"

tasks:
  build:
    desc: Build the box binary
    cmds:
      - go build -o box main.go

  build-linux:
    desc: Build the box binary for linux
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o box main.go

  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  test-integration:
    desc: Run integration tests
    cmds:
      - go test -v -tags=integration ./...

  coverage:
    desc: Show test coverage summary
    cmds:
      - |
        echo "Test Coverage Report"
        echo "===================="
        printf "%-40s | %-10s\n" "Package" "Coverage"
        echo "-----------------------------------------|-----------"
        go test -tags=integration -cover ./... | grep "coverage:" | while read -r line; do
          pkg=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($i ~ /github.com\/sebakri\/box/) print $i}')
          cov=$(echo "$line" | awk '{for(i=1;i<=NF;i++) if($i ~ /[0-9]+\.[0-9]%/) print $i}')
          pkg_short=$(echo "$pkg" | sed 's|github.com/sebakri/box/||' | sed 's|github.com/sebakri/box|.|')
          if [ -n "$pkg_short" ] && [ -n "$cov" ]; then
            printf "%-40s | %-10s\n" "$pkg_short" "$cov"
          fi
        done
        echo "-----------------------------------------|-----------"
        go test -tags=integration -coverprofile=coverage.out ./... > /dev/null
        TOTAL=$(go tool cover -func=coverage.out | grep "total:" | awk '{print $3}')
        printf "%-40s | %-10s\n" "TOTAL" "$TOTAL"

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  serve-docs:
    desc: Serve documentation
    cmds:
      - go run . run mkdocs serve

  install:
    desc: "Install box on this machine"
    cmds:
      - go build -o box main.go
      - sudo mv box /usr/local/bin/box

  tag:internal:
    internal: true
    cmds:
      - |
        if [ -z "{{.TAG}}" ]; then
          echo "Error: TAG variable is required"
          exit 1
        fi
        if git rev-parse "{{.TAG}}" >/dev/null 2>&1; then
          echo "Tag {{.TAG}} already exists"
        else
          git tag {{.TAG}}
          echo "Created tag {{.TAG}}"
        fi

  release:
    desc: "Create a release. BUMP can be 'next' (default), 'patch', 'minor', or 'major' (usage: task release [BUMP=minor])"
    vars:
      FINAL_TAG:
        sh: svu {{default "next" .BUMP}}
    cmds:
      - |
        if [ "{{.FINAL_TAG}}" == "$(svu current)" ]; then
          echo "No version bump required"
          exit 1
        fi
      - task: tag:internal
        vars: { TAG: "{{.FINAL_TAG}}" }
      - git push origin main --tags

  "release:patch":
    desc: "Create a patch release"
    cmds:
      - task: release
        vars: { BUMP: patch }

  "release:minor":
    desc: "Create a minor release"
    cmds:
      - task: release
        vars: { BUMP: minor }

  "release:major":
    desc: "Create a major release"
    cmds:
      - task: release
        vars: { BUMP: major }

  changelog:
    desc: "Show changelog for the next release"
    vars:
      LAST_TAG:
        sh: git describe --tags --abbrev=0 2>/dev/null || echo ""
    cmds:
      - |
        if [ -z "{{.LAST_TAG}}" ]; then
          echo "No previous tags found. Showing all commits:"
          git log --oneline --no-merges
        else
          echo "Changelog since {{.LAST_TAG}}:"
          echo ""
          for type in feat fix refactor perf docs chore; do
            LOGS=$(git log {{.LAST_TAG}}..HEAD --oneline --no-merges --grep="^$type")
            if [ -n "$LOGS" ]; then
              case $type in
                feat) echo "### Features ✨" ;;
                fix) echo "### Bug Fixes 🐛" ;;
                refactor) echo "### Refactoring 🛠️" ;;
                perf) echo "### Performance ⚡" ;;
                docs) echo "### Documentation 📚" ;;
                chore) echo "### Maintenance 🧹" ;;
              esac
              echo "$LOGS" | sed 's/^[a-f0-9]* /- /'
              echo ""
            fi
          done
          # Show others that don't match standard types
          OTHERS=$(git log {{.LAST_TAG}}..HEAD --oneline --no-merges | grep -vE "^[a-f0-9]+ (feat|fix|refactor|perf|docs|chore)(\(.*\))?:")
          if [ -n "$OTHERS" ]; then
            echo "### Other Changes"
            echo "$OTHERS" | sed 's/^[a-f0-9]* /- /'
            echo ""
          fi
        fi
