version: "3"

tasks:
  build:
    desc: Build the box binary
    cmds:
      - go build -o box main.go

  build-linux:
    desc: Build the box binary for linux
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o box main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  serve-docs:
    desc: Serve documentation
    cmds:
      - go run . run mkdocs serve

  install:
    desc: "Install box on this machine"
    cmds:
      - go build -o box main.go
      - sudo mv box /usr/local/bin/box

  tag:auto:
    desc: "Create a new tag based on commits"
    cmds:
      - |
        NEXT_TAG=$(svu next)
        if [ "$NEXT_TAG" != "$(svu current)" ]; then
          git tag $NEXT_TAG
          echo "Created tag $NEXT_TAG"
        else
          echo "No version bump required"
        fi

  release:
    desc: "Create a tag and push to trigger release"
    cmds:
      - task: tag
      - git push origin main --tags

  changelog:
    desc: "Show changelog for the next release"
    vars:
      LAST_TAG:
        sh: git describe --tags --abbrev=0 2>/dev/null || echo ""
    cmds:
      - |
        if [ -z "{{.LAST_TAG}}" ]; then
          echo "No previous tags found. Showing all commits:"
          git log --oneline --no-merges
        else
          echo "Changelog since {{.LAST_TAG}}:"
          echo ""
          for type in feat fix refactor perf docs chore; do
            LOGS=$(git log {{.LAST_TAG}}..HEAD --oneline --no-merges --grep="^$type")
            if [ -n "$LOGS" ]; then
              case $type in
                feat) echo "### Features ✨" ;;
                fix) echo "### Bug Fixes 🐛" ;;
                refactor) echo "### Refactoring 🛠️" ;;
                perf) echo "### Performance ⚡" ;;
                docs) echo "### Documentation 📚" ;;
                chore) echo "### Maintenance 🧹" ;;
              esac
              echo "$LOGS" | sed 's/^[a-f0-9]* /- /'
              echo ""
            fi
          done
          # Show others that don't match standard types
          OTHERS=$(git log {{.LAST_TAG}}..HEAD --oneline --no-merges | grep -vE "^[a-f0-9]+ (feat|fix|refactor|perf|docs|chore)(\(.*\))?:")
          if [ -n "$OTHERS" ]; then
            echo "### Other Changes"
            echo "$OTHERS" | sed 's/^[a-f0-9]* /- /'
            echo ""
          fi
        fi
